repository: mhiro2/nagori

coverage:
  paths:
    - apps/desktop/coverage/lcov.info

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-desktop-report

comment:
  if: is_pull_request
  hideFooterLink: false

summary:
  if: is_pull_request
  hideFooterLink: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-desktop-report
